spring:
  application:
    name: postgresql-demo
  datasource:
    url: jdbc:postgresql://192.168.153.128:5432/runoobdb?&ssl=false
    username: postgres
    password: postgres
mybatis:
  mapper-locations: classpath:/mapper/*.xml