server:
  port: 8010
spring:
  profiles:
    active: mq,db
  rabbitmq:
    host: 192.168.153.128
    port: 5672
    username: xbang
    password: xbang
    virtual-host: /spring-test
    publisherConfirms: true
    publisher-returns: true

logging:
  level:
    com:
      xbang: trace