spring:
  datasource:
    db1:
      username: java_opr
      password: Soar18786611964!
      url: jdbc:mysql://47.104.171.254:3306/java_db?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false