
spring:
  application:
    name: spring-db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: java_opr
    password: Soar18786611964!
    url: jdbc:mysql://47.104.171.254:3306/java_db?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
    #profiles:
    # active: dynamic
  #profiles:
  #  active: dynamic

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xbang.mybatis.dao.entity
logging:
  level:
    com:
      xbang:
        mybatis:
          dao:
            mapper: trace
