server:
  port: 8050



spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.171.254:3306/number_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    username: root
    password: Soar18786611964

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com:
      xbang:
        mybatis:
          mapper: trace
