
multi:
  datasource:
    enabled: true
    key: master
    datasource:
      master:
        url: jdbc:mysql://47.104.171.254:3306/java_db?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
        user-name: root
        password: Soar18786611964_
        class-name: com.mysql.cj.jdbc.Driver
      slave:
        url: jdbc:mysql://47.104.171.254:3306/demo?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
        user-name: root
        password: Soar18786611964_
        class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081